version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: barbar-book
    ports:
      - '5434:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
